repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Use the latest commit on the master branch
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: '23.11.0'  # Use the latest commit on the master branch
    hooks:
      - id: black
        args: ['dinov2']
  # - repo: https://github.com/pycqa/pylint
  #   rev: ''  # Use the latest commit on the master branch
  #   hooks:
  #     - id: pylint
  #       args: ['--exit-zero', 'dinov2']
